@startmindmap

<style>
mindmapDiagram {
    node {
        Padding 12
        Margin 10
        LineColor #4D4D4D
        BackgroundColor #4D4D4D
        FontColor white
        Shadowing 0
        HorizontalAlignment center
    }
    arrow {
        LineStyle 0
        LineColor #4D4D4D
    }
}
</style>

+ PVE 系統框架

<style>
  node {
    BackGroundColor #E85642
    LineColor #E85642
  }
</style>
++ 應用技術
+++ Golang
+++ Redis
+++ AWS EC2

<style>
  node {
    BackGroundColor #FFC300
    LineColor #FFC300
  }
</style>
++ 常駐服務
+++ 系統復原
+++ 心跳檢測
+++ 斷線重連

<style>
  node {
    BackGroundColor #155384
    LineColor #155384
  }
</style>
-- 核心單元
--- 牌局管理模組
--- 封包處理模組
--- 機器人模組

<style>
  node {
    BackGroundColor #12AAB5
    LineColor #12AAB5
  }
</style>
-- 網路單元
--- 後端溝通模組
--- 資料庫存取模組

<style>
  node {
    BackGroundColor #55AA59
    LineColor #55AA59
  }
</style>
-- 邏輯單元
--- 遊戲規則模組
--- 演出風格模組
--- 牌局分析模組

@endmindmap